{% set name = "NotebookScripter" %}
{% set version = "6.0.0" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c4acc888b160e4f7dc46bfb4f4c700101e5bae4f8a211021ccb4f1bd139fd5c7

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - ipython
    - nbformat

test:
  imports:
    - NotebookScripter

about:
  home: https://github.com/breathe/NotebookScripter
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Expose ipython jupyter notebooks as callable functions.  More info here https://github.com/breathe/NotebookScripter
  description: "Expose ipython jupyter notebooks as callable functions.  More info here https://github.com/breathe/NotebookScripter\n\n\n"
  doc_url: https://github.com/breathe/NotebookScripter
  dev_url: https://github.com/breathe/NotebookScripter

extra:
  recipe-maintainers:
    - breathe
