travis:
  secure:
    BINSTAR_TOKEN: GReMz88V9hjWf0IaHqwBxCphj0hFm+Eegnr6VvRK4VImpAQxPsoCe652iSqk4Cwt5S+05w6PA/CCTS+2Xy6CAUtwyYZeeFSZGNS35B+RUExUwJ+Ej4RTg3GQ/MbEmKxk43BzzhxwfIKk5Ni/SCvIf/PScpVoH4WXFrNXl//tc36MRJeB9xd1j2tyGw6RJMjE1X0Cs4EGjuDLgxadNOB/4+SgMwWozYnQ0dLpo7LG4whU8VKPLPGlhXs33fslF2g3+BNNzA7KPiv02MdzS7EgQfFxpCu7veMXeuNJG86RvRpJKXP4rJVidXLYo6cU6czzosRZdLPWLvQHLVzamWtKdSi1mzqdW7ZIoWsf94Hbgck7RjgAIMdskZUGcysGGbUBo7KzEAIUb+vx+msjn0LxkLMaXU4kREPD3avD9NPyimgTBPcIHukBbmrmIcxaFFTTdOZKNmLgWAdro2PseHFXb0XcQbozbmuBE8ADvIX19nyAUWfURfkRpZ1XJb8eo0fjDjiamqckzmJQHZQ2Z8HKOuKOrirGxtNqWuv+qqfAneJsC3LsBAURyu0BadO4/9mkr4WQu3ju1NNqvFhKBvHR6lt7e2BmbBI65H1RvPxCUttTxoXmyDR1cpQzntnMw4byxyO/mKUlCPflNTRi4MevN/0uyHNl7kBX6HybM5yoYLM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
